MultiFQtoVC.nf

Samtols 1.3 is installed on irma by now, it is bwa and java8 that was left out. These changes are needed to keep the milou and irma versions in sync.

bwa and java version changed so it is the same on milou and irma

---

MultiFQtoVC.nf

Note: Lots of changes are ATOM editor removing trailing whitespace by default, so might be harder than usual to read :)
The problem at the moment seems to be that if sample.tsv contains more than one normal file far too many processes are submitted by nextflow for haplotypecaller.

adding HC, fixing nopreprocessing, removing -nct from mutect2

---

MultiFQtoVC.nf
README.md
config/milou.config

Changes in this PR:
- added examples to restart processing after preprocessing
- fixed a channel duplication bug
- renamed MuTect1 output
- enabling trace and timeline generation by default (it is actually not working yet)

README example, channel duplication fix

---

MultiFQtoVC.nf
README.md

So I propose to keep in `Preprocessing`, copies of non-recalibrated and recalibrated files (respectively in `NonRecalibrated` and `Recalibrated` directories).
It both directories there are of course accompanying TSV files.
And then if the pipeline worked without problems, to use `nextflow clean -f` to get rid of the temp files.
`nextflow clean -f` remove all the temp files from the lastest run, but keep some folders (I guess it'll get better in future versions). 
cf issue #46

Cleaning intermediate files

---

main.nf

Recent `samtools sort` versions support reading SAM from stdin (they still write BAM output). In my tests, leaving out this line gives a binary identical BAM file in the end, but is roughly 10% faster. The speedup comes from getting rid of one compression/decompression round (`samtools view` compresses its output, which is then immediately decompressed by `samtools sort`).

Speed up mapping by not running samtools view

---

scripts/merge_callers.py

This script can be used to merge SNVs called by MuTect1, MuTect2 and Strelka. 
**Usage:**
/path/to/merge_callers.py samplename MuTect1_vcf MuTect2_vcf Strelka_vcf
where 
samplename is set by the user
MuTect1_vcf, MuTect2_vcf and Strelka_vcf are the outputs from the three SNV callers. 
For Strelka you should use the file "passed.somatic.snvs.vcf". 
**What it does:**
- Filters the MuTect1 and MuTect2 calls based on flags in the respective vcf files. 
For MuTect1: all snvs marked with "REJECT" are skipped. 
For MuTect2: snvs marked with all types of flags described in the original MuTec2 vcf file are       skipped (flags are hard coded based on what was in the test data Jan-Feb 2017)
No additional filter applied to Strelka calls as the "passed.somatic.snvs.vcf" are already filtered. 
- Takes …

Added file "merge_callers.py" in scripts folder

---

scripts/merge_callers.py

Now extracts genotyping columns for tumor and normal based on the order between the samples in the definition row (the one starting with #chrom ....). 
Earlier version of the script assumed that tumor data was in column 9 and normal data was in column 10, but this was not OK for MuTect1. 
Fixed column numbers are probably OK for MuTect2 and Strelka because these programs have "NORMAL" and "TUMOR" as header and the order seem to be the same in all tested files. 
MuTect1 uses the tumorid and normalid as headers and the order between them is different between samples, so they really need to be parsed. 
Now I'm parsing the genotype columns for tumor and normal in all VCF files, either by looking for the tumorid and normalid (MuTect1) or for "NORMAL" and "TUMOR" (Strelka and MuTect2). 
fix …

Fix in merge_callers.py

---

README.md
configuration/docker-skadi.config
configuration/docker-test.config
configuration/docker.config
doc/ASCAT.md
doc/FOLDER.md
doc/INSTALL.md
doc/PROCESS.md
doc/REFERENCES.md
doc/TOOLS.md
doc/TSV.md
doc/USAGE.md
doc/USE_CASES.md
main.nf
nextflow.config
test/test_skadi_docker.sh

/!\ WARNING /!\
Breaking compatibility with older version, so I propose to go directly to version 1.1
- Change --steps to --step and --tools
Only one step between `preprocessing`,`realilgn`,`recalibrate` and `skipPreprocessing`
And --tools to specify wich tools to be use.
Help updated.
Docker container updated.
Links to CAW website.
Refactoring:
- replace `workflowSteps` by `step` and `tools`
- add function `defineReferenceForProcess(process)` to define reference files for each process (the long term plan is to verify only the references needed and not all, and try to download/build them then if needed)
- rename `bam` to `mappedBam` to clarify code
- use `map.key` notation to access maps instead of `map['key']`
- Channels `duplicatesRealign` and `intervals` are now phased to …

Refactoring for version 1.1

---

main.nf

The default mismatch penalty is 4. Probably the idea is that tumor reads
have more mismatches. This should not apply to normal samples, and we need
BWA default parameters if this pipeline is to be used for normal samples.

Do not adjust BWA mismatch penalty for normal samples

---

main.nf

Problem:
```
nextflow run main.nf -profile localhost --test
ERROR ~ No signature of method: java.lang.String.join() is applicable for argument types: (java.lang.String) values: [, ]
Possible solutions: wait(), trim(), find(), wait(long), split(java.lang.String), count(java.lang.CharSequence)
-- Check script 'main.nf' at line: 1553 or see '.nextflow.log' file for more details
```
Line 1553 contains `tools.join(...)`. If no `--tools` was given on the command-line,
then tools is an empty string (`''`). An empty string does not have a `.join` method.

Fix error message when no --tools parameter given

---

main.nf

The expression `!a in b` is not the same as `!(a in b)`. The former
negates a and then tests for membership, which is not what was
intended.

Fix incorrect membership tests

---

main.nf

`status` is a string, so all samples were processed without `-B 3`

corrected condition for extra for cancer sample in BWA

---

main.nf

I need these changes in order to be able to add a `--sampleDir` option (that does not require a TSV). Perhaps some of the code could even be moved into a setup function, but that’s for later.

Refactor set up of input files (--sample vs --test)

---

configuration/localhost.config
configuration/uppmax-genomes.config
configuration/uppmax.config
nextflow.config

Simplified configuration of bundle paths by using string interpolation, and also put everything into a single file that is then included by all the profiles that need it.

Simplify genome configuration

---

configuration/uppmax-genomes.config
main.nf

The index files are now defined through a path with wildcards. They are no longer listed one by one, which makes it possible to have the GRCh37 version without and the GRCh38 with the .alt index file. This also simplifies the configuration.
With this change, BWA-MEM will run in ALT-aware mode.
This PR breaks the docker configuration files, but I will leave that to @MaxUlysse, who is working on #240 anyway.

ALT-aware mapping

---

configuration/genomes.config
main.nf

Merge configuration settings kgIndels and millsIndels into a single knownIndels, which is a list of VCF file names. We need this flexibility for other references such as GRCh38 which do not necessarily have the same number of VCF files with known indels.
See other commit messages for more changes.

Flexible indel list

---

configuration/genomes.config

According to the (probably outdated) workflow at
https://github.com/broadinstitute/wdl/blob/7e6f95b09221658911c35547b9ba5031013b7a63/scripts/broad_pipelines/PublicPairedSingleSampleWf_160927.inputs.json
they use Mills_and_1000G_gold_standard.indels.hg38.vcf.gz and
Homo_sapiens_assembly38.known_indels.vcf.gz as known indel VCFs.
Unfortunately, the latter file is in the beta/ subdirectory of their
hg38bundle, whatever that means.

Use same known indels for GRCh38 as Broad

---

main.nf

... by adding a few more `set -euo pipefail` where they did not exist, yet. The second commit converts some stray tabs to spaces.

 Ensure errors make the pipeline fail more consistently

---

configuration/docker.config
configuration/localhost.config
configuration/uppmax-slurm.config
configuration/uppmax.config
main.nf

This renames the CreateIntervals process to RealignerTargetCreator, and the RealignBams process to IndelRealigner.
I have not renamed the other processes because I find the name of the process actually clearer than the GATK names. For example, GATK BaseRecalibrator does *not* recalibrate bases, but only create the recalibration table, so CreateRecalibrationTable is appropriate IMO.

Clearer naming of some GATK processes

---

configuration/genomes.config
doc/GENOMES.md
main.nf

Previously, nearyl all GATK tools were called with `-XL`, which is `--excludeIntervals`. It was set to `-XL hs37d5 -XL NC_007605` in order to exclude decoys and the Epstein-Barr sequence. These names are specific to GRCh37, however. With this change, we use `-L` instead, we gives a list of all intervals to *include*`. For some tools that already before got an explicit list of intervals to work on, this change just removes the `-XL` parameters as they should not have had any effect anyway.
(Need to check this: In addition, it seems that this makes `--test` runs faster because the set of intervals is restricted to a much smaller subset.)

Include instead of exclude intervals to work on

---

main.nf

This reduces the number of temporary files that are created. The default is
768 MB, now it is 4 GB. Files on disk were just ca. 180 MB, which means that
hundreds of files are created for a final BAM that has perhaps 50 GB.
An even nicer solution would be to use as much memory as is available minus
about 8 GB for BWA-MEM.

Use more memory for samtools sort

---

configuration/genomes.config

Parsing the file will fail otherwise.
GATK supports multiple formats (also the .interval_list format), but since
we parse the interval list ourselves, it’s easier to work with the .list
format for both genome versions (GRCh37 and GRCh38).
How to convert .interval_list to .list is documented in GENOMES.md

Use interval list in .list format for GRCh38

---

configuration/genomes.config
configuration/uppmax.config

When adding a new genome, one currently needs to edit both uppmax.config
and genomes.config. With bundleDir also in genomes.config, only one file
needs to be customized.
Closes #270

Move bundleDir into genomes.config

---

main.nf

According to
https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller.php
the option is set to 0 anyway when --emitRefConfidence GVCF is used:
> When running in `-ERC GVCF` or `-ERC BP_RESOLUTION` modes, the
> emitting and calling confidence thresholds are automatically set
> to 0. This cannot be overridden by the command line.

Remove unused -stand_call_conf option to HaplotypeCaller

---

configuration/genomes.config

I haven’t tested this since I’m not using Cosmic, but the path should be fine.
The file has been generated by @Sebastian-D

Add path to COSMIC GRCh38 VCF

---

main.nf
nextflow.config

`set -eu` is already enabled by Nextflow, but `-o pipefail` is missing.
See discussion at nextflow-io/nextflow#151

 Enable set -euo pipefail by default for all shells

---

buildReferences.nf
configuration/docker.config
configuration/localhost.config
configuration/uppmax.config
main.nf
test/test_docker.sh

Removed VarDictHome.
UPPMAX use PATH wrapper for directory inside the VarDictJava installation.
And they also installed VarDict inside the VarDictJava installation (which is also wrapped inside PATH).
So cleaned the path to the scripts inside this directory
Inside the ConcatVCF process:
Change the use of `var2vcf_somatic.pl` to `var2vcf_paired.pl` as it is deprecated cf https://github.com/AstraZeneca-NGS/VarDict/issues/46
and gzip the final file
close #271

VarDictJava clean up

---

bin/run_ascat.r
main.nf

1) I moved the R code in process "RunAscat" to a separate script in CAW/bin/run_ascat.r
This script is called in main.nf exactly like in process "RunConvertAlleleCounts".
2) Ascat now creates an additional file with the actual CNV regions. This file is created in the R-code in CAW/bin/run_ascat.r
The output file is called idSampleTumor.cnvs.txt and has the following format:
chr     startpos        endpos  nMajor  nMinor
1       30863705        30867104        4       3
1       56128724        56133074        9       6
2       79748960        81240737        2       1
where the columns contain
1) Chromosome
2) start position of CNV region
2) end position of CNV region
4) Number of copies of "major allele" for this region (major and minor alleles are arbitrary)
5) Number of copies of "minor …

Change in Ascat

---

configuration/docker.config
configuration/localhost.config
configuration/uppmax.config
main.nf

The process gets HaplotypeCaller’s genomic VCFs (.g.vcf) files as
input and converts them to regular VCFs. This is done on the interval-split
VCF files. Both the normal and the genomic VCF are then passed to ConcatVCF
in order to create whole-genome VCFs. The output is written to
VariantCalling/HaplotypeCaller.
This makes makes the pipeline a bit slower, and I have not tested by how much. However, I hope that I can improve ConcatVCF speed (see #305), and then we are hopefully back to the original runtime.
Feel free to wait with merging until I have run this on a full dataset.

 Add a RunGenotypeGVCFs process

---

configuration/genomes.config
scripts/sort_intervals.py

I’ve created a new `.list` file using the included script and added it to the hg38bundle directory on Uppmax. The script parses a trace.txt file and outputs a new (sorted) .list file.
I have not run that script for GRCh37.
Processing time goes down from 8h 11m to 7h 22m.
Closes #292

Sort intervals of calling regions by processing time

---

main.nf

The awk command reads in the full file (checking every line whether it is a
header line). The sed command stops on the first non-header line.

When extracting the VCF header, do not read the entire file

---

main.nf

With this, ConcatVCF (with tool=='haplotypecaller') on genomic VCFs is down to
3h30m from previously 3h50m.

Use parallel gzip (pigz) whenever possible

---

scripts/test_docker.sh

Previously, the script would just continue if one of the commands failed. This is avoided by using set -e in the header.
The second change is to use `-x` as well to avoid printing all the commands by hand.

Make tests actually fail if one of the test commands failed

---

scripts/sort_intervals.py

Durations without seconds such as "57m" were parsed as 0 seconds.
I have also regenerated the `wgs_calling_regions_sorted.hg38.list` file.

Fix regex used in parsing durations in trace.txt

---

main.nf
scripts/test_docker.sh

When HaplotypeCaller is the only requested tool, the pipeline now skips the RecalibrateBam process.
The option --BQSR is directly passed to HaplotypeCaller. This means that HaplotypeCaller does the base quality recalibration "on the fly". The results should be the same as before.
To clarify: Base quality recalibration is still done, we just never create the BAM file with recalibrated bases.
PrintReads, which was previously used to create the recalibrated BAM file, took around 19 hours. With this change, and when only HaplotypeCaller is run, these 19 hours are saved. HaplotypeCaller is a bit slower because it needs to recalibrate bases on-the-fly , but this is distributed over all HaplotypeCaller processes running in parallel (working on separate intervals). For calling variants on a full …

Do not explicitly create a recalibrated BAM if HaplotypeCaller is the only tool being run

---

scripts/makeSnapshot.sh

Differences in behavior:
- HEAD is packaged, not the working copy
- The final tar.gz is written to the current directory, not one directory up
Closes #333

Simplify the makeSnapshot script

---

configuration/localhost.config
configuration/uppmax.config
main.nf

Instead of using Picard’s SortVcf, we can simply concatenate the VCFs in the correct order. This works because we know that the VCFs do not overlap each other and because each of them is already sorted.
The ConcatVcf process previously took around 4-5 hours. One hour was spent in concatenating all files (with awk), much of the rest on Picard’s SortVcf, and some time on compressing the output.
With this change, ConcatVcf needs 5 minutes to create a 12 GB GVCF file, which previously took around 4 hours. This is not a typo.

Reduce ConcatVCF runtime on GVCF from 4 hours to 5 minutes

---

configuration/genomes.config

We were asking for `GRCh38.86`, but only `GRCh38.82` is available on bianca, so obviously it fails...

hotfix for snpeff with GRCH38

---

main.nf

Local variable should always declared specifying a type or alternative by using the `def` keyword (type inferred by the assigned) otherwise they will defined in the script global scope possibly overriding variables having the same name.

Declare variables as local

---

main.nf

This kind of assignment is unnecessary, moreover the assignment can override a variable with the same name in the global scope.

Fix possible conflicts

---

main.nf

The `create` method is not necessary when assigning a channel with the `into` or any other operator (it's only needed when it need to specified as a parameter, as with the `choice` operator).

Removed unnecessary create

---

doc/USE_CASES.md
main.nf
scripts/test_docker.sh

Only a defined list of tools triggers the recalibrated BAM to be created.
Previously, we would check only whether HaplotypeCaller is the only tool
being run, but that is too restrictive. Now, the RecalibrateBam step is
also omitted with --tools=HaplotypeCaller,MultiQC, for example.

Skip RecalibrateBam step in more situations; make skippreprocessing work

---

main.nf

The VCF header was not parsed correctly (it worked only on GRCh38)

Fix ConcatVCF on GRCh37

---

README.md

That way, we will less likely forget about it and remember to update it too when we update CAW.

add information about biotools in README

---

buildReferences.nf
main.nf

- `helpMessage()`, `startMessage()` and `versionMessage()` now take no argument as `revision` can be find using `this.grabRevision()`, and `$version` was already global.
- add `cawMessage()`, `minimalInformationMessage()` and `nextflowMessage()` to display messages that are repeated in other messages.
- change `checkFile()`, `checkStatus()` and `checkTSV()` to `returnFile()`, `returnStatus()` and `returnTSV()` respectively

simplified messages

---

main.nf

I'm considering that if we choose `--step recalibrate` we do really want the recalibration to happen, and so `explicitBqsrNeeded` is set to true, in any other case, I'm sticking with what was already done.
It could definitively be improved, but at least it fixes the problem we were having.

fix recalibrate

---

scripts/test_singularity.sh

Singularity is not working with `openjdk7`, so our MuTect1 container is not working.
- removed it from tests
- remove typos (leftover from excessive copy/paste)

remove mutect1 from tests + fix typo

---

.travis.yml
scripts/install.sh
scripts/test.sh

- Add a new install script
- Use it to install Nextflow in the install step
- Install Singularity (but in the script step) only when testing with Singularity
- Remove containers only when running on TravisCI
The idea is to be able to run this testing script for all tests (on personal computers and on Travis).
By default the test will be a singularity test.

Install Singularity on TravisCI only when necessary

---

configuration/localhost.config

This cleans up the `localhost.config` file a bit:
The most important change is that the default is to request 1 cores and 8 GB of memory, and that the exceptions to that need to be configured. Before, the defaul twas to request 16 cores and the full memory of a node.
Also, I’ve set `maxForks = 16` for *all* processes. Nextflow will already make sure that the launched processes do not use more memory and CPU cores than available, so `cpus` and `memory` will already limit the number of launched processes at a time. One reason to use `maxForks` could be to reduce I/O, but this should not be relevant for this configuration where the pipeline runs on a single node.

Resource configuration cleanup

---

main.nf

The ##contig header fields are optional and some variant callers don’t
output them (including older versions of FreeBayes).

Fix ConcatVCF: Use .fai for contig names, not VCF header

---

main.nf

- remove name of intervals
- use file.baseName to get the string
- remove unnecessary variables that were passed through ConcatVCF and never used anywhere

Simplify operations on bedIntervals and intervals in general

---

configuration/uppmax-localhost.config

ConcatVCF does not need much memory and giving it more than 8 cores
does not make it faster.

Reduce ConcatVCF resources to sane levels

---

main.nf

Closes #454 
I would have liked to use `Channel.isEmpty()` because it has such an obvious name, but it is unclear to me how that would work.

Write an error message when --sampleDir does not find any FASTQ files

---

buildContainers.nf
configuration/containers.config
configuration/singularity-path.config
containers/vcftools/Dockerfile
containers/vcftools/environment.yml
doc/BUILD.md
doc/CONTAINERS.md
doc/PROCESS.md
germlineVC.nf
runMultiQC.nf
scripts/do_all.sh
scripts/test.sh
somaticVC.nf

close #368 
- New `vcftools` container
- New `RunVcftools` process
- Update output from `ConcatVCF` process
- Actually use all VCFs in the reports

Add VCFtools

---

somaticVC.nf

RunManta changed so that bam and bai files are no longer added to publishDir (results/Manta)

Bam files for manta no longer saved (but still channeled to strelka)

---

doc/TESTS.md
scripts/test.sh
somaticVC.nf

Some output was not there anymore due to #579

Fix Manta output

---

configuration/binac.config
nextflow.config

Added the configuration for the german BinAC cluster.

Binac addition

---

containers/gatk4/Singularity
scripts/selectROI.py

The official GATK4 docker container is pretty bloated, so I made a Singularity-only one that is about 10% in size of the version created from docker. 
Also this PR contains hotfixes for the ROI script to make it work correctly with the CLC viewer.

GATK4 Singularity container and fixes for ROI

---

annotate.nf
germlineVC.nf
lib/QC.groovy
somaticVC.nf

Simplification of channels.
Output is now:
- `_snpEff.ann.vcf.gz` instead of `.snpEff.ann.vcf.gz`
- `_VEP.ann.vcf.gz` instead of `.vep.ann.vcf.gz`
- `_snpEff_VEP.ann.vcf.gz` instead of `.snpEff.ann.vcf.vep.ann.vcf.gz`

Code polishing for Compress Annotated VCFs

---

configuration/uppmax-localhost.config
configuration/uppmax-slurm.config
main.nf

This PR improves the execution of FastQC so that it uses one thread per fastq file as described in #631.
Tests do not pass. But I highly suspect that is due to my personal setup for some reason. Travis checks should give a final decision.

2 threads and 2 cpus for each FastQC process

---

.github/RELEASE_CHECKLIST.md
CHANGELOG.md
README.md
annotate.nf
buildReferences.nf
conf/containers.config
conf/singularity-path.config
conf/uppmax-localhost.config
conf/uppmax-slurm.config
docs/CONFIG.md
docs/INSTALL.md
docs/OUTPUT.md
docs/PROCESS.md
docs/REFERENCES.md
docs/USAGE.md
docs/USE_CASES.md
germlineVC.nf
main.nf
runMultiQC.nf
somaticVC.nf

- Closes #633 
- Clean comments
- Clean docs
- rework the version gathering system

Update more Docs

---

CHANGELOG.md
runMultiQC.nf

Process `GetVersionAll` was not working.
2 different issues:
- Not launching when nothing in `directoryMap.version`
-Fixed by adding `.ifEmpty(file ("empty"))` to the input channel
- `samtools` and `vcftools` where not giving out versions, and somehow blocking the execution of the rest of the process.
- Fixed by adding `2>&1 || true` after launching each tool

Fix RunMultiQC error

---

CHANGELOG.md
main.nf

- input bam file has always the same name in the MarkDuplicates process
before, it was called `runId.bam` for single pair fastq and `sampleId.bam` for multiple pairs fastq

input bam file has always the same name

---

CHANGELOG.md
buildContainers.nf

- process `PullSingularityContainers` was expecting a `.img` file, but since we're now using the correct `.simg` extension for singularity images, it was an issue

fix expected output of PullSingularityContainers process

---

CHANGELOG.md
annotate.nf
buildContainers.nf
buildReferences.nf
conf/base.config
docs/PARAMETERS.md
lib/SarekUtils.groovy
main.nf
runMultiQC.nf
somaticVC.nf

- add `publishDirMode` param to make possible to choose the mode of publishDir directive
- add docs
- close #669

add publishDirMode param and docs

---

CHANGELOG.md
annotate.nf
conf/aws-batch.config
conf/containers.config
conf/genomes.config
conf/singularity-path.config
germlineVC.nf
somaticVC.nf

- change path for `genome_base`
- change queue for awsbatch
- add container for `CreateIntervalBeds`
- add `publishDirMode` for `germlineVC.nf`

Awsbatch modifications

---

conf/base.config
nextflow.config

This moves the `check_max` function to the main `nextflow.config`. We had issues when using the current `cfc` profile on our cluster to resolve the function properly, thus creating errors such as this one:
```
Completed at: Fri Nov 02 10:10:45 CET 2018
Duration    : 6s
Success     : false
Exit status : null
Error report: Error executing process > 'MapReads (QMSHSENTITY-2-_L004_)'
Caused by:
No signature of method: _nf_script_64002d7c.check_max() is applicable for argument types: (Integer, String) values: [10, cpus]
```
Manually adding the function to `nextflow.config` resolved the error for us.

Move `check_max` function to `nextflow.config`

---

annotate.nf
main.nf

outDir was in fact used twice in PublishDir for some process

fix PublishDir for some process

---

CHANGELOG.md
conf/aws-batch.config
conf/containers.config
conf/genomes.config
conf/singularity-path.config
conf/uppmax-localhost.config
conf/uppmax-slurm.config
germlineVC.nf
lib/QC.groovy
main.nf
somaticVC.nf

Following @parlundin request:
- Use more cpus in parrallel
- Add some extra flags
- Add one extra BAMQC process to run on the mapped bams

Enhance Qualimap BAMQC

---

CHANGELOG.md
conf/aws-batch.config
conf/base.config
conf/genomes.config
conf/igenomes.config
docs/REFERENCES.md
nextflow.config

- add a specific iGenomes config file

iGenomes specific config file

---

CHANGELOG.md
environment.yml

Update FastQC and add fonts

---

CHANGELOG.md
main.nf

- Fix #704 
- `--TMP_DIR` was replaced by `--tmp-dir` at some point between GATK `4.0.6.0` and `4.0.9.0`

replace --TMP_DIR by --tmp-dir in BaseRecalibrator to close #704

---

CHANGELOG.md
main.nf

- removed old channels and comments
- The second BamQC (and samtools stats) are now run on the recalibrated BAMs (before it was on the MarkDuplicates)

Run bamQC on the recalibrated BAMs

---

CHANGELOG.md
somaticVC.nf

- Fix Ascat ref file input (one file can't be a set)

fix input for RunAscat (was not a set)

---

CHANGELOG.md
main.nf

- bamQC outputs are no longer overwritten

fix BAMQC output

---

conf/binac.config
conf/cfc.config
nextflow.config

This PR aims to update the `cfc.config` and the `binac.config` to set a genome_base and `nextflow.config` to allow `cfc` and `binac` to use an `igenomes` setup.

update cfc and binac genome_base and singularity version

---

CHANGELOG.md
germlineVC.nf
somaticVC.nf

- check only for references that are needed
- fix #754

Check for needed reference only

---

CHANGELOG.md
conf/base.config

Currently there are references to `task.mem` in the script sections e.g. for `HaplotypeCaller`. 
When a local standard executor is used or when there is no definition of the process attributes in the configuration files `task.mem` is `null`. 
Therefore functions such as `task.mem.toGiga()` fail.
To fix this behaviour this PR includes a minimal definition for process resources. 

add minimal process.cpu .mem and .time definition

---

CHANGELOG.md
main.nf

- Autogenerates memory requirements from MarkDuplicates when less that 8G is available
- from https://github.com/nf-core/rnaseq/pull/179

Markdup java options

---

CHANGELOG.md
annotate.nf
containers/vepgrch37/environment.yml
containers/vepgrch38/environment.yml
docs/ANNOTATION.md
docs/CONTAINERS.md
environment.yml
germlineVC.nf
lib/QC.groovy
lib/SarekUtils.groovy
somaticVC.nf

- Adding the possibility to use the VEP GeneSplicer plugin
- VCFs from Manta won't over write any more
- Add new `reduceVCF()` function to remove `.ann`, .`gz` and `.vcf` from a vcf file name

Further improvments on VEP

---

CHANGELOG.md
docs/USE_CASES.md
main.nf

This should address https://github.com/SciLifeLab/Sarek/issues/794 in the end, writing some docs for it now 👍 And testing it locally on some data to figure out whether this really helps ;-)

Fix 0.0X Coverage for targeted Data
