SciLifeLab/Sarek

- MultiFQtoVC.nf
- README.md
> manta 1.0.0

- LICENSE
- MultiFQtoVC.nf
Remove intervals for Strelka process
Issue #77
> remove Strelka intervals

- MultiFQtoVC.nf
- config/milou.config
See also #79 . It is the first PR on that line.
> First attempt to optimize CPU and memory usage

- README.md
- doc/UPPMAX.md
- main.nf
Replaced `touch ../../../Preprocessing/NonRecalibrated/${idPatient}.tsv`
by `touch $baseDir/Preprocessing/NonRecalibrated/${idPatient}.tsv`
> Corrected typo and errors in pathways

- main.nf
- forgot `status` on `CreateIntervals` process
- simplification on handling `Channels` for `ConcatVCF` process
- better handling of files as list for `VarDict` for `ConcatVCF` process
- corrected `checkFileExistence` output
> Corrections

- README.md
- configuration/milou.config
- main.nf
- fix #126 
- fix bug with bai instead of bam in CreateIntervals
- with bug when only variantCalling steps given
- add badge passing nextflow > 0.22.2 (milou version)
> Correct issue with Manta and BAM header

- configuration/milou-local.config
- main.nf
- Corrected quotation marks in milou-local.config
- Corrected typos
- Changed reference file in RunStrelka process (which was still MantaRef) and fix #127
- Changed `params.intervals` for `referenceMap['intervals']`
> All tests on test tiny set works on interactive

- main.nf
> updated RunAscat so that all output files are copied to output dir

- README.md
- configuration/milou.config
- doc/PROCESS.md
- doc/USAGE.md
- main.nf
- Change MultiQC version so it now works on milou (there was some FIFO problems between older version and Nextflow so they where both waiting each other forever...)
- Add MultiQC to --test
- Fix issue #152
- Fix issue #155 
- Update README files
> MultiQC working

- configuration/milou-slurm.config
- configuration/milou.config
- configuration/standard.config
- main.nf
@MaxUlysse plz have a look, tiny tests are OK
> Better resource management, also unified java version

- configuration/bianca-slurm.config
- configuration/bianca.config
- main.nf
- nextflow.config
@MaxUlysse pls have a look: I had to change to readlink in the strelka config, should not affect milou, but bianca FS was not happy with links. Also the single CPU memory is 7G, seems we have issues with this value on milou, see #163
> Changes related to bianca core test runs

- main.nf
- nextflow.config
- processVCFs.nf
- scripts/addCallerINFO.awk
- scripts/fixMantaContigs.awk
- scripts/makeIntersectAndUnion.sh
@MaxUlysse Having this flow we can i) rough filter calls (retaining only PASS-ed ones), also tag each line with a caller names, and merge calls.
> Workflow to tag and merge VCFs

- README.md
- configuration/docker-test.config
- configuration/docker.config
- doc/FIRST_RUN.md
- main.nf
- nextflow.config
- test/test_skadi_docker.sh
- got rid of version number in `README.md` (using releases/latest badge)
- add `configuration/docker-test.config` for testing
- change docker images version to match CAW's version
- update help with more information about references files
- removed MuTect1 output
- add tests
> Enhance help for usage outside UPPMAX

- doc/FIRST_RUN.md
- fix typo
- Add link to UPPMAX export URL for the last 3 Reference Files
> Add UPPMAX export for Reference Files

- configuration/bianca-slurm.config
- configuration/bianca.config
- configuration/milou-slurm.config
@MaxUlysse these are mostly changes related to bianca only. I will have to update java eventually as they just added the sun_jdk1.8.0_92, but I will do after tried ASCAT
> config changes related to bianca to make it in sync with milou

- configuration/bianca.config
- configuration/localhost.config
- configuration/milou.config
- main.nf
@MaxUlysse small changes mostly related to bianca
> changes related to bianca run optimisation

- configuration/bianca.config
- configuration/localhost.config
- configuration/milou.config
- main.nf
@MaxUlysse should be more config-file related
> Memory adjustment for HaplotypeCaller, also modularising local config

- configuration/bianca.config
- configuration/localhost.config
- configuration/milou.config
- main.nf
The only issue is that MuTect2 is not deriving genotype names from the BAM file, so I submitted a question. @MaxUlysse you still can merge it until answer (if there is any) arrives.
> Concatenating VCFs works for the default GATK variant callers

- main.nf
That way, we're sure we have the right file for the right step.
-> in the `extract*` functions
Also add which version of the genome is used in the logs (`workflow.onComplete`, workflow.onError` and MultiQC config)
> Add file extension checking function for files listed in the tsv file

- main.nf
In particular, do not use `assert` when an `if` suffices.
Also changed this construct
```
a = condition ? value : a
```
to
```
if (condition) {
a = value
}
```
because I find it suprising that it ends up self-assigning `a` to `a` when the condition is false.
> Simplify logic in multiple places

- nextflow.config
.. my fault, forgot this when merging bianca/milou configurations
> Fix interactive profile referring to non-existent file

- main.nf
It is not a list anymore.
Closes #224
> Turn "step" into a scalar

- main.nf
#223 corrected expression in if statements.
So now the condition are met and we have a warning.
So removing all these lines because these statements were in fact useless..
> get rid of close warning

- main.nf
No need to display a line without any information in the logs
> display tools information only if a tool is selected

- main.nf
> convert status to int

- main.nf
Tip from Paolo on the Nextflow gitter channel
> Local variable

- main.nf
This adds the option `--sampleDir`, which is mutually exclusive with `--sample` and `--test` (only one of the three may be given).
Wildcards are supported, so `'--sampleDir=my/directory/with/samples/*'` works. Each directory is then treated as a single patient with a single sample.
Also, add a function `flowcellIdFromFastq()`, which extracts the flowcell ID from a FASTQ file. This is at the moment only used with `--sampleDir`, not when on `--sample` or `--test` is provided.
> A directory of FASTQs can be given with --sampleDir

- configuration/uppmax-genomes.config
This works already somewhat: Merged BAM files are created.
Mapping is not ALT-aware and GATK fails, but hey, it’s a start!
> Add GRCh38 to genome configuration

- main.nf
This brings us very close to the `@RG` header format as used by NGI.
> Also detect the lane from the FASTQ file

- configuration/docker.config
- configuration/genomes.config
- main.nf
typos in #240 are corrected
Added a function to check Genome version.
> Correct config files typo

- main.nf
This moves the knowledge about which reference files a process requires
directly into the definition of the process. It is thus no longer
necessary to edit two locations in the code when changing or adding a
process. It also gets rid of many temporary variables that are used only once.
> Refactor: Get rid of defineReferenceForProcess

- main.nf
> add checkParams() function

- main.nf
> add isAllowedParams()

- README.md
- main.nf
> add marcelm to contributors + remove old tests

- main.nf
Have tested on small, works, so I will merge and start working on the DREAM data.
> verbose FreeBayes options

- README.md
- configuration/docker.config
- configuration/genomes.config
> Moving bundleDir out of docker.config

- buildReferences.nf
- configuration/docker.config
- configuration/genomes.config
- configuration/localhost.config
- configuration/testing.config
- configuration/uppmax.config
- doc/GENOMES.md
- main.nf
- test/test_docker.sh
In `buildReferences.nf`:
- use params.genome
- add --download option to force download of smallRef
- add --refDir option to give path to smallRef if it's not possible to download automatically (like on Bianca).
Update GENOME.md with informations about smallGRCh37 and `buildReferences.nf`
Update `test_docker.sh` script with new options
> buildReferences.nf update

- configuration/localhost.config
- configuration/testing.config
- configuration/uppmax-slurm.config
- configuration/uppmax.config
- sort processes
- remove last bundleDir that was out of genomes.config
- add module for RunVEP (fixes #290)
> Arrange config

- doc/REFERENCES.md
- scripts/Create_Cosmic.sh
Adds info to REFERENCES.md regarding how to create your own COSMIC.vcf compatible with mutect1/2 for any reference.
Adds script Create_Cosmic.sh which is used in the aforementioned creation.
> Update REFERENCES.md and add Create_Cosmic.sh

- buildReferences.nf
If all the following files are in the given folder, this script will extract and build all the indexes needed:
- `1000G_phase1.indels.b37.vcf.gz`
- `1000G_phase3_20130502_SNP_maf0.3.loci.tar.bz2`
- `b37_cosmic_v74.noCHR.sort.4.1.vcf.tar.bz2`
- `dbsnp_138.b37.vcf.gz`
- `human_g1k_v37_decoy.fasta.gz`
- `Mills_and_1000G_gold_standard.indels.b37.vcf.gz`
- `centromeres.list`
> add possibility to build GRCh37

- main.nf
> move test for project after help and version messages

- doc/USAGE.md
- main.nf
> Case sensitivity

- main.nf
This reduces I/O. I have not found a way to stream the input as well.
Runtime for ConcatVCF went down from 4h 22m to 3h 48m on the data set I tested it (a GRCh38 one).
> Stream Picard SortVcf output into gzip

- main.nf
Fix #309 on milou, will try on Bianca next
> fix Vep on milou

- buildReferences.nf
I'd love to have submodules, so I can't reuse more easily functions.
> add help for buildReferences.nf + fix #311

- configuration/localhost.config
- configuration/uppmax.config
- main.nf
the problem was only in the modules (we didn't add VarDictJava to the modules to load for the process...)
And forgot some modules for ConcatVCF.
> Fix VarDict on milou #312

- configuration/docker.config
cf https://www.nextflow.io/docs/latest/config.html#scope-docker
> add fixOwnership flag to fix ownership of files created by the docker container

- main.nf
I’m trying to understand the code a bit better. While doing so, I found a few things that should improve readability. See individual commit comments. I can split this up into multiple PRs if desired.
> Some cleanups

- main.nf
- test/test_docker.sh
Hot fixes for Variant Callers induces by latest changes on PR #316
will be merged ASAP
> fix Variant Callers issue with changes for gender handling

- configuration/localhost.config
104 GB will work both on milou and bianca
> Decrease requested memory to a reasonable value

- .travis.yml
- scripts/test_docker.sh
- test/test_docker.sh
- In `.travis.yml`: `nextflow` is moved to `/usr/local/bin/`
- In `test_docker.sh`: Use `nextflow` instead of `./nextflow`
- `test_docker.sh` moved to `scripts/`
- Better cleaning of containers
> Better travis testing

- makeSnapshot.sh
- scripts/makeSnapshot.sh
- moved makeSnapshot.sh to scripts/
- add exclude for `doc/SprintReview*`
- add exclude for `References*`
> Sort out makeSnapshot script

- main.nf
This is a leftover from "Avoid sending the gender into all processes" (part of #316).
> Fix: VCF grouping for concatenation did not work

- scripts/test_docker.sh
This adds a function that wraps `nextflow run`
> Simplify the test script

- configuration/docker.config
- configuration/localhost.config
- configuration/testing.config
- configuration/uppmax-modules.config
- configuration/uppmax.config
- nextflow.config
See individual commit comments.
> Simplify configuration

- scripts/pDist.py
Sometimes when ConcatVCF crashes, there can be corrupt VCF files (hoping not anymore). This script is to report regions with missing calls
> Smal script to check VCF files

- doc/INSTALL.md
- doc/INTERVALS.md
> Add help on how to install CAW on Bianca

- main.nf
Previously, the contig names 1..22, X and Y were hardcoded.
@malinlarsson With this change, the ConcatVCF step also includes the `GL...` contigs.
> Use contig names from VCF header for merging VCFs

- README.md
PR #393 was fixing other faulty links, but not the one reported by #392 
It's now corrected...
Thanks to @pditommaso for figuring it out
> finally really fixing #392

- doc/INSTALL_SINGULARITY.md
- scripts/test_docker.sh
- scripts/test_singularity.sh
Regarding singularity, better explanations concerning the containers to download or not.
> Improve README

- configuration/uppmax-modules.config
- main.nf
- scripts/test_docker.sh
> Fix problems with VEP

- main.nf
Fixed an excessive copy+paste...
> Fix VEP verbose output

- scripts/test_docker.sh
- scripts/test_singularity.sh
Adding more testing in TravisCI:
- Annotation (VEP + snpEff) for Strelka
- Annotation (VEP + snpEff) for MuTect2
- Annotation (snpEff) for Manta
> More tests

- doc/INSTALL_CONTAINERS.md
- doc/USE_SINGULARITY_BIANCA.md
switch docker-hub container for Mutect1 with an image based on `openjdk:7-slim` instead of `openjdk:7`
> Mutect1 now working with Singularity

- configuration/docker.config
- main.nf
- Using old container for gatk
- Fix output for VEP
> Fix containers

- configuration/singularity-download.config
- main.nf
And some additional fixes, like added GenerateMultiQCconfig container and generating CONTIGS from the FASTA file at ConcatVCF
> added VEP changes to accomodate verbose output

- buildReferences.nf
- doc/INSTALL_MILOU.md
- main.nf
- closes #434 
- fix a small bug due to #431
> Update installation on milou procedure

- main.nf
The prefix is now determined automatically.
> Remove unused variable chrPrefix

- configuration/docker.config
- configuration/singularity.config
- configuration/uppmax-modules.config
- main.nf
- scripts/test.sh
> Compress VCFs with bgzip and index them with tabix

- main.nf
As recommended: https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals
Closes #440
> Add option -L to BaseRecalibrator

- main.nf
Display information about all reference files used in the output and in the MultiQC report
> Display more informations

- scripts/skeleton_batch.sh
There was an extra `-with-trace` in the `skeleton_batch.sh` script
> remove extra -with-trace

- configuration/singularity-download.config
Change concatVCF container for htslib
> hotfix for concatvcf container

- configuration/uppmax-localhost.config
> Give the local executor more than 1 CPU

- doc/USE_CASES.md
> Document use of the --sampleDir option

- doc/Abstracts/PMC_2018.md
≤ 2500 characters (authors and affiliations included...)
> Add abstract for Precision Medicine in Cancer Conference

- .gitignore
- README.md
I rewrote the readme to be a little more structured and less a big block of text. Hopefully now it's a little easier to skim read :)
Please check that what I've written is correct, especially the list of tools used.
Probably easier to read the new readme as rendered on [my fork](https://github.com/ewels/Sarek/blob/master/README.md).
> Readme refactoring

- germlineVC.nf
- scripts/wrapper.sh
- somaticVC.nf
- add verification of non-empty channel for normal or tumor channels
- remove case structure for handling sample, since only one case left...
- correct `wrapper` basic bash script
> Add checking for existing tumor/normal channel

- annotate.nf
Quick fix for #533 
Replace VEP `--pick` option by `--per_gene`
cf https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick
> replace --pick by --per_gene to close #533

- README.md
> Updated readme docs links to Github formatted pages instead of raw

- annotate.nf
- buildContainers.nf
- buildReferences.nf
- germlineVC.nf
- main.nf
- runMultiQC.nf
- somaticVC.nf
Change version to 2.0.0 in the script.
@szilvajuhos When the tests are OK, we can merge and publish the draft release for 2.0.0.
> update to 2.0.0

- annotate.nf
- configuration/base.config
- configuration/containers.config
- configuration/singularity-path.config
- lib/SarekUtils.groovy
- scripts/test.sh
- somaticVC.nf
new PR to replace #467 
This is deactivated by default.
So it should be safe to merge if we want to try this new feature
> Follow Strelka BP and use Manta small indels candidates as input

- .travis.yml
cf https://github.com/NBISweden/K9-WGS-Pipeline/blob/master/.travis.yml#L10-L18
> improve TravisCI readability

- .travis.yml
- remove `gnomon` for Travis CI testing
> remove gnomom that is not very usefull in fact and hide failing tests

- doc/Abstracts/2018-06-EACR25.md
> EACR25 abstract

- .travis.yml
- scripts/install.sh
> Fix Singularity installation on Travis CI

- configuration/base.config
- lib/SarekUtils.groovy
- main.nf
Add custom CN field in BAM files with BWA when creating the files.
Only if a `sequencing_center` params is defined.
cf @ewels 
cf @sven1103 @apeltzer (it could of interest for you as well)
PS: Thanks to @Rotholandus for making me work on that ;-)
> Add custom CN field in BAM files

- .gitmodules
- CHANGELOG.md
- Add [pathfindr](https://github.com/NBISweden/pathfindr) as a submodule
> add pathfindr as a submodule

- CHANGELOG.md
- Dockerfile
- Singularity
- conf/base.config
- environment.yml
> Preparing release 2.2.0

- CHANGELOG.md
- scripts/do_release.sh
- add VERSION XX.YY.ZZ inside `Singularity` file to `do_release.sh` script
> Update do_release script

- CHANGELOG.md
- conf/binac.config
- conf/cfc.config
- conf/resources.config
- nextflow.config
This adds configuration for Tuebingen infrastructure (BinAC cluster, CFC Cluster) and adds a more generic resource config for these resources. We can get this for others up as well, but it works quite nicely here on the servers. I also added the new `publishDirMode` params automatically :-)
> Add Tuebingen specific configuration parameters

- conf/resources.config
This simply updates the `resources.config` to reflect the minor changes required on our two clusters to make it run well. With this change, everything we tried so far ran through well and without issues.
> Minor changes to resources.config

- docs/REFERENCES.md
This just updates a bit more details on the GRCH38 genome reference building process. I might work on adding the GRCH38 genome to the `buildReferences.nf` script if you want that... ?
> Better GRCH38 Documentation for input files

- conf/binac.config
This adds the updated singularity module of binac cluster here in Tuebingen.
> Fix for updated binac cluster module

- conf/base.config
- conf/resources.config
- lib/SarekUtils.groovy
- main.nf
This is a tested change on ~5 Exomes, based on comments by @alneberg and @MaxUlysse in the Sarek gitter chat. Having this as a default worked very well for us.
> MarkDuplicates tested options

- CHANGELOG.md
- Dockerfile
- Singularity
- environment.yml
- nextflow.config
> preparing release 2.2.2

- CHANGELOG.md
- Dockerfile
- buildReferences.nf
- containers/r-base/Dockerfile
- Removed no longer used function
- Small typo fixed
> small fixes

- CHANGELOG.md
- conf/munin.config
> update munin configuration

- docs/README.md
Fixed dead link in the input / tsv documentation
> fix dead link in documentation README

- .travis.yml
- CHANGELOG.md
- germlineVC.nf
- scripts/test.sh
- somaticVC.nf
- Added `--exome` for Manta, and for StrelkaBP
- Added Travis CI test for targeted
> Add --exome for Manta for WES

- CHANGELOG.md
- Dockerfile
- Singularity
- containers/snpeffgrch37/Dockerfile
- containers/snpeffgrch37/environment.yml
- containers/snpeffgrch38/Dockerfile
- containers/snpeffgrch38/environment.yml
- containers/vepgrch37/Dockerfile
- containers/vepgrch37/environment.yml
- containers/vepgrch38/Dockerfile
- containers/vepgrch38/environment.yml
- environment.yml
- nextflow.config
- scripts/do_release.sh
> prepare 2.3 release

- CHANGELOG.md
- add Unreleased section in CHANGELOG
> Preparing next release ;-)

- conf/binac.config
- conf/cfc.config
Fixed missing params variable name. Sorry for the typo.
> fix typo in cfc binac config

- CHANGELOG.md
- conf/igenomes.config
- typo in iGenomes smallGRCh37 config
> Another typo

- CHANGELOG.md
- containers/r-base/Dockerfile
- containers/runallelecount/Dockerfile
- germlineVC.nf
- somaticVC.nf
- Added `ps` in `r-base` and `runallelecount` containers
Issue discussed on gitter with @lconde-ucl
> Added `ps` in `r-base` and `runallelecount` containers

- CHANGELOG.md
- runMultiQC.nf
- add `|| true` for all tools when gathering versions
> add || true for all tools when gathering versions

- CHANGELOG.md
- conf/munin.config
- main.nf
- nextflow.config
- fix `genome_base` path in `munin.config`
- fix `markdup_java_options` definition
- include `conf/resources.config` in `btb` profile
> Fix some bugs on munin

- CHANGELOG.md
- conf/munin.config
- nextflow.config
- improve munin configuration (cpus, memory and time wise)
> Improve munin configuration

- CHANGELOG.md
- lib/SarekUtils.groovy
- main.nf
- Add possibility to use `fq.gz` too
- Fix #797
> Can handle both fastq.gz and fq.gz

- containers/vepgrch37/Dockerfile
- containers/vepgrch37/environment.yml
- containers/vepgrch38/Dockerfile
- containers/vepgrch38/environment.yml
- environment.yml
- Change version back to `95.2`
- Should fix current tests
> fix VEP containers

- bin/convertAlleleCounts.r
- bin/run_ascat.r
- conf/munin.config
- Fix Path to Rscript in `convertAlleleCounts.r`
> fix path to Rscript

- docs/ASCAT.md
Many thanks to contributing to Sarek!
Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).
> fix: Update link to ASCAT loci file for GRCh37
